Feature/add square page
squadster/squadster-frontend pull request #7
Opened 2020-03-20 18:41 UTC by str1nker

2020-03-21 21:37 UTC, ARtoriouSs commented
Lets move squad number a little down and right to be in the center

![image](https://user-images.githubusercontent.com/33663194/77237013-3cc57100-6bd5-11ea-8915-15c64124b72d.png)

2020-03-21 21:39 UTC, ARtoriouSs commented
On mobile view commanders and deputy commanders shifted, probably we can move role text on the top of member card

![image](https://user-images.githubusercontent.com/33663194/77237021-5bc40300-6bd5-11ea-8c2b-01409c560408.png)

2020-03-21 21:45 UTC, ARtoriouSs commented
Also lets remove this sorts:

![image](https://user-images.githubusercontent.com/33663194/77237089-fae8fa80-6bd5-11ea-8118-9352787ed684.png)

We can just put commander, deputys and journalist to the top, and below will be students in order of duty like [here](https://aginvlad.github.io/VzvodApp/)

2020-03-21 21:49 UTC, str1nker commented
> On mobile view commanders and deputy commanders shifted, probably we can move role text on the top of member card
> 
> ![image](https://user-images.githubusercontent.com/33663194/77237021-5bc40300-6bd5-11ea-8c2b-01409c560408.png)

@ARtoriouSs  reload the page

2020-03-21 22:00 UTC, ARtoriouSs requested changes

2020-03-21 22:00 UTC, ARtoriouSs commented on src/components/Navbar.jsx
> -  const classes = useStyles();
I think we need semicolons here and below

2020-03-24 21:10 UTC, ARtoriouSs approved these changes

2020-03-24 21:10 UTC, merged

2020-03-24 21:11 UTC, ARtoriouSs commented
nice!