feature/squad creator component
squadster/squadster-frontend pull request #9
Opened 2020-04-05 13:47 UTC by TanyaAkulich

2020-04-09 16:19 UTC, ARtoriouSs requested changes
Looks good!

2020-04-09 16:19 UTC, ARtoriouSs commented on src/components/NewSquad.jsx
> +              Отправляйте запросы на вступление и ожидайте подтверждения командира взвода. Мы уведомим вас как только ваша заявка будет подтверждена.
I think it's better to use
`Отправьте запрос на вступление ...`
because user can only send one request

2020-04-18 19:38 UTC, ARtoriouSs commented
Everything is fine, lets just add validations for input

2020-04-18 21:10 UTC, str1nker requested changes

2020-04-18 21:10 UTC, str1nker commented on src/components/NewSquad.jsx
> +  }
please do not use `window.location.reload` . As I remember I changed that in my commit here, incorrect conflict resolution?

2020-04-21 16:41 UTC, str1nker requested changes

2020-04-21 16:41 UTC, str1nker commented on src/components/NewSquad.jsx
> +  const [sendRequest] = useMutation(SET_SQUAD, { onCompleted: () => window.location.href ='/my-squad' });
Need to fix this

2020-04-21 18:36 UTC, merged